# Change prefix to match Vim leader key (kinda useless ngl)
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Add binding to reload tmux config easily
bind -n "M-r" source-file ~/.tmux.conf ';' display "Tmux config reloaded!"
bind r        source-file ~/.tmux.conf ';' display "Tmux config reloaded!"

# Allow scrolling using mouse wheel
set -g mouse on

# Numbering window and pane
set  -g base-index       1
setw -g pane-base-index  1
set  -g renumber-windows on

# Split plane horizontal/vertical
bind -n "M-\\"  split-window -h  -c "#{pane_current_path}"
bind -n "M-|" split-window -fh -c "#{pane_current_path}"

bind -n "M--"  split-window -v  -c "#{pane_current_path}"
bind -n "M-_"  split-window -fv -c "#{pane_current_path}"

# Move to another window
bind -n "M-="     last-window
bind -n "M-."     next-window
bind -n "M-," previous-window

# Move to another pane
bind -n "M-Up"    select-pane -U
bind -n "M-Down"  select-pane -D
bind -n "M-Left"  select-pane -L
bind -n "M-Right" select-pane -R

# Resize to another pane
bind -n "M-k" resize-pane -U 2
bind -n "M-j" resize-pane -D 2
bind -n "M-h" resize-pane -L 5
bind -n "M-l" resize-pane -R 5

bind -n "M-n" resize-pane -x 86

# Close pane/window
bind -n "M-w" kill-pane

# Create new window
bind -n "M-t" new-window -c "#{pane_current_path}"
