# Add binding to reload tmux config easily
bind r source-file ~/.tmux.conf \; display "Tmux config reloaded!"

unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

# Numbering window and pane
set  -g base-index       1
setw -g pane-base-index  1
set  -g renumber-windows on

# === PANES ===
# Back to last panes
bind Space last-window

# Split plane horizontal/vertical
bind "|"  split-window -h  -c "#{pane_current_page}"
bind "\\" split-window -fh -c "#{pane_current_page}"

bind "-"  split-window -v  -c "#{pane_current_page}"
bind "_"  split-window -fv -c "#{pane_current_page}"
