# preload = ~/Pictures/Wallpaper/DarkForest8Bit.png
# preload = ~/Pictures/8-bit-graphics-pixels-scene-with-airport.jpg

preload = ~/Pictures/Wallpaper/CityNight8Bit.jpg
preload = ~/Pictures/Wallpaper/8Bit-City1.png
preload = ~/Pictures/Wallpaper/8Bit-City2.jpg

wallpaper = , ~/Pictures/Wallpaper/8Bit-City2.jpg
